kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-injector-webhook
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "update", "patch", "delete"]

